#!/bin/bash
docker compose down
echo "y" | docker volume prune

docker compose up --detach --build

sleep 30
docker container exec mariadb1 bash -c "mariadb -uroot < /tmp/init/01.sql"
docker container exec mariadb2 bash -c "mariadb -uroot < /tmp/init/01.sql"
docker container exec mariadb3 bash -c "mariadb -uroot < /tmp/init/01.sql"

sleep 30
./reset_replication
